### ISSUE TITLE
Update astropy in the suggested environments

### ISSUE THREAD

**Issue by bsipocz** [LSSTDESC/plasticc-kit#2]
There was a bug recovered in astropy that prevented it being able to read in `test_set.csv` the way suggested in the starter kit notebook. 
Now it has been fixed and will be included in the new bugfix released in the next few days (2.0.9 and 3.0.5).

Please update the version number in the environment /requirements files if possible. 

I can ping you again when the releases are out if that's helpful.

**Comment by gnarayan** [comment]
Thanks @bsipocz - I've seen the updated releases, but they don't look to be on PyPI or pkgs/main or conda-forge yet. Can you ping me when these are available, and I'll update the env files and the `requirements.txt` file?  I didn't actually have any issues reading `test_set.csv` so not clear what the issue was.

**Comment by gnarayan** [comment]
I saw a conda update on OSX, so pushed this change. I also updated i686 file, but admittedly haven't checked that yet.

**Comment by bsipocz** [comment]
I yet to send out the release announcement, but nevertheless the release should be available on the default conda channel as well as with pip from pypi.

Thanks for updating the requirement here.
